name: spfx-build-deploy

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "*"
    exclude:
      - az-pipelines/*
      - _images/*

variables:
  sppkg: devops-wp.sppkg
  # set runtime vars: username, password

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: Build SPFx
        pool:
          vmImage: "ubuntu-20.04"
        steps:
          - template: templates/spfx-build.yaml
            parameters:
              nodeVersion: $(12)
              artifactName: $(sppkg)

  - stage: Deploy
    displayName: Deploy to M365
    dependsOn: Build

    jobs:
      - deployment: DeployM365
        displayName: Deploy to M365
        environment: M365Prod
        strategy:
          runOnce:
            deploy:
              steps:
            
              - task: NodeTool@0
                displayName: use node 12.x
                inputs:
                  versionSpec: 12.x
                  
              - task: Npm@1
                displayName: 'npm i -g @pnp/cli-microsoft365'
                inputs:
                  command: custom
                  verbose: false
                  customCommand: 'install -g @pnp/cli-microsoft365'
              
              - script: |
                  m365 login -t password -u $(username) -p $(password)                  
                displayName: 'Connect to M365'

              - script: 'm365 spo app add -p $(Agent.BuildDirectory)/drop/sharepoint/solution/$(sppkg) --overwrite'
                displayName: 'Upload to App Catalog'

              - script: 'm365 spo app deploy --name $(sppkg)'
                displayName: 'Deploy App'