name: test-agent-spfx

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "FoodListSPFx/*"

pool:
    name: aci-pool      

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: "ubuntu-20.04"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 10.x
            displayName: Install Node.js
          - task: CmdLine@2
            displayName: npm install
            inputs:
              script: "npm install"
              workingDirectory: "FoodListSPFx/"

          - task: gulp@1
            displayName: "gulp bundel"
            inputs:
              gulpFile: "FoodListSPFx/gulpfile.js"
              targets: "bundle"
              arguments: "--ship"
              enableCodeCoverage: false

          - task: gulp@1
            displayName: "gulp package solution"
            inputs:
              gulpFile: "FoodListSPFx/gulpfile.js"
              targets: "package-solution"
              arguments: "--ship"

          - task: CopyFiles@2
            displayName: "Copy Files to: $(build.artifactstagingdirectory)/drop"
            inputs:
              Contents: "FoodListSPFx/sharepoint/solution/*.sppkg"
              TargetFolder: "$(build.artifactstagingdirectory)/drop"

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifacts: drop"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/drop"